# Generated by Django 4.2.20 on 2026-01-17 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gpt_app', '0002_chat_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('daily_chat_count', models.IntegerField(default=0)),
                ('total_chats', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chat_data',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='chat_data',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='chat_data',
            index=models.Index(fields=['user', '-timestamp'], name='gpt_app_cha_user_id_cc7b64_idx'),
        ),
        migrations.AddIndex(
            model_name='chat_data',
            index=models.Index(fields=['session_id'], name='gpt_app_cha_session_11c716_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
