# Generated by Django 4.2.20 on 2026-01-17 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gpt_app', '0003_userprofile_alter_chat_data_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Conversation', max_length=255)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='chat_data',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat_data',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat_data',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat_data',
            name='regeneration_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='model_name',
            field=models.CharField(default='TinyLlama/TinyLlama-1.1B-Chat-v1.0', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='system_prompt',
            field=models.TextField(blank=True, default='You are a helpful AI assistant.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='temperature',
            field=models.FloatField(default=0.7, help_text='Model temperature: 0.0-2.0'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='top_p',
            field=models.FloatField(default=0.9, help_text='Top-p sampling: 0.0-1.0'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=10),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat_data',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='gpt_app.conversation'),
        ),
        migrations.AddIndex(
            model_name='chat_data',
            index=models.Index(fields=['conversation'], name='gpt_app_cha_convers_6e566d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-updated_at'], name='gpt_app_con_user_id_3adee5_idx'),
        ),
    ]
